name: firebase_upgrader
description: "A Flutter package for managing feature flags using Firebase Realtime Database."
version: 1.0.3
homepage: https://github.com/karrarfalih/firebase_upgrader

environment:
  sdk: '>=2.12.0 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  firebase_feature_flag: ^1.0.9
  flutter:
    sdk: flutter
  package_info_plus: '>=1.0.0 <=7.0.0'
  url_launcher: '>=6.1.0 <=6.2.6'

dev_dependencies:
  flutter_test:
    sdk: flutter
    
flutter:
